/*
 * This source file was generated by the Gradle 'init' task
 */
package create_project;

import processing.core.PApplet;

public class Main extends PApplet{

    public void settings(){
        size(800, 800);
    }

    public void setup(){
        size(800, 800);
        background(0);
        frameRate(60);
        GameInstance.getInstance().setGraphics(createGraphics(800,800));
    }

    public void draw(){
        GameInstance.getInstance().draw();
        image(GameInstance.getInstance().getGraphics(), 0, 0);
    }

    public void mousePressed(){

	}
	
	public static void main(String[] args){
		String[] processingArgs = {"MySketch"};
		Main app = new Main();
		PApplet.runSketch(processingArgs, app);
	}
}