/*
 * This source file was generated by the Gradle 'init' task
 */
package create_project;

import processing.core.PApplet;

public class Main extends PApplet{

    public void settings(){
        size(400, 400);
    }

    public void setup(){
        background(0);
        noStroke();
    }

    public void draw(){
        fill(255);
        ellipse(mouseX, mouseY, 20, 20);
    }

    public void mousePressed(){
		background(64);
	}
	
	public static void main(String[] args){
		String[] processingArgs = {"MySketch"};
		Main app = new Main();
		PApplet.runSketch(processingArgs, app);
	}
}