/*
 * This source file was generated by the Gradle 'init' task
 */
package create_project;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void test() {
        assertTrue(true);
    }
}
